[tool.poetry]
name = "uzen"
version = "0.1.0"
description = "YARA with Puppeteer"
authors = ["Manabu Niseki <manabu.niseki@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
aiofiles = "^0.5.0"
aiomysql = "^0.0.20"
aiosqlite = "^0.13.0"
alembic = "^1.4.2"
async_lru = "^1.0.2"
certifi = "^2020.4.5"
dnspython = "^1.16.0"
fastapi = "^0.55.1"
fastapi-utils = "^0.2.1"
httpx = "^0.12.1"
ipwhois = "^1.1.0"
loguru = "^0.5.0"
pydantic = "^1.4"
pyopenssl = "^19.1.0"
pyppeteer2 = "^0.2.2"
pysafebrowsing = "^0.1.1"
python-whois = "^0.7.2"
requests-html = "^0.10.0"
tortoise-orm = "^0.16.4"
uvicorn = "^0.11.3"
yara-python = "^4.0.0"

[tool.poetry.dev-dependencies]
asynctest = "^0.13.0"
autoflake = "^1.3.1"
autopep8 = "^1.5.1"
black = "^19.10b0"
coveralls = "^2.0.0"
flake8 = "^3.7.9"
isort = "^4.3.21"
mypy = "^0.770"
mysqlclient = "^1.4.6"
pre-commit = "^2.2.0"
pytest = "^5.4.1"
pytest-asyncio = "^0.12.0"
pytest-black = "^0.3.8"
pytest-cov = "^2.8.1"
pytest-mock = "^3.1.0"
pytest-randomly = "^3.3.1"
pytest-timeout = "^1.3.4"
respx = "^0.10.1"
seed-isort-config = "^2.1.0"
vcrpy = "^4.0.2"

[tool.isort]
force_grid_wrap = 0
include_trailing_comma = true
known_third_party = ["OpenSSL", "alembic", "certifi", "dns", "fastapi", "fastapi_utils", "httpx", "ipwhois", "loguru", "pydantic", "pyppeteer", "pysafebrowsing", "pytest", "requests", "requests_html", "respx", "sqlalchemy", "starlette", "tortoise", "tqdm", "urllib3", "vcr", "whois", "yara"]
line_length = 88
multi_line_output = 3
use_parentheses= true

[build-system]
requires = ["poetry-core>=1.0.0a5"]
build-backend = "poetry.core.masonry.api"
